### ISSUE TITLE
Torus Wallet currency exchange rate display error

### ISSUE THREAD

**Issue by refiny** [Web3Auth/Web3Auth#201] opened 2022-05-26 14:40 UTC
### **Describe the bug**

After login in to torus wallet , click open wallet, my current eth balance and the target currency USD exchange rate display error

### **To Reproduce**

1. Login into Torus
2. Click on 'Open wallet'

### **Expected behavior**

ETH and the target exchange rate display currect.

### **Screenshots**

![image](https://user-images.githubusercontent.com/15261334/170510855-8d4fd9a6-51f8-45ff-8361-fbad1ee02d38.png)

### **Device Info (please complete the following information):**

- Device: Desktop
- OS: Windows11
- Browser: chrome
- Version: 103
- Web3Auth Version: 1.0.0

### **Additional context**

-

**Comment by refiny** [comment] 2022-05-26 14:45
After I relogin again, the balance currency is still not currect.

![image](https://user-images.githubusercontent.com/15261334/170512226-04dcb427-0928-4b15-819b-f0ea6e8fc3ad.png)

**Comment by tainguyentt** [comment] 2022-05-27 08:23
Hi @refiny it's due to that you're using the Test Network. If you switch to Main Network, the exchange rate will be correct.
I'm not sure if we have an exchange rate for ETH in testnet?

**Comment by refiny** [comment] 2022-05-27 13:46
This issue is happend in recent version upgrade, could you please check those configuration to make the currency display currect in testnet.
below screenshot is the payment confirm page we usuallly use in mobile model. 
![608b1a42db2120eb88ec4eb81d5263c](https://user-images.githubusercontent.com/15261334/170711467-3441ad03-94c6-47cb-b959-c1b57db6e851.jpg)

**Comment by tainguyentt** [comment] 2022-05-30 09:05
I'm thinking that this can be caused by the API to get the currency `https://api.tor.us/currency?fsym=ETH&tsyms=USD` is rate limited so the exchange rate is fallback to default value 1 USD

```{"Response":"Error","Message":"You are over your rate limit please upgrade your account!","HasWarning":false,"Type":99,"RateLimit":{"calls_made":{"second":1,"minute":3,"hour":13,"day":2081,"month":149822,"total_calls":864397},"max_calls":{"second":50,"minute":2500,"hour":25000,"day":50000,"month":100000}},"Data":{}}```

**Comment by himanshuchawla009** [comment] 2022-06-10 04:35
it is fixed now, closing it.

**Closed by himanshuchawla009** 2022-06-10 04:35 UTC
